name: cargic_user
description: Cargic

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


# packages // front end
  cupertino_icons: ^1.0.0
  flutter_svg: ^0.19.1
# packages //back end
  firebase_core: ^0.5.0+1
  firebase_auth: ^0.18.1+2
  google_sign_in: "^4.5.1"
  firebase_database: ^4.1.1
  google_maps_flutter: ^1.0.3
  flutter_polyline_points: ^0.2.4
  geolocator: ^5.3.1
  http: ^0.12.2


  # packages // helpers
  provider: ^4.3.2+2
  connectivity: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:


  uses-material-design: true

  # Image assets
  assets:
    - images/
  #   - images/a_dot_ham.jpeg

  
  #  font assets
  fonts:
    - family: Niramit
      fonts:
        - asset: fonts/Niramit-Regular.ttf
        - asset: fonts/Niramit-Italic.ttf
        - asset: fonts/Niramit-Bold.ttf
  #         style: italic
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Regular.ttf
        - asset: fonts/Nunito-Italic.ttf
        - asset: fonts/Nunito-Bold.ttf

  #         weight: 700
    - family:  CargicIcons
      fonts:
       - asset: fonts/CargicIcons.ttf
    - family:  CargicSecondaryIcons
      fonts:
       - asset: fonts/CargicSecondaryIcons.ttf

 
        
